name: mood_tracker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.6
  image_picker: ^0.8.7+5
  table_calendar: ^3.0.9
  intl: ^0.18.1
  screenshot: ^2.1.0
  share_plus: ^7.0.1
  drift: ^2.8.0
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.0.15
  path: ^1.8.3
  shared_preferences: ^2.1.1
  fl_chart: ^0.62.0
  cupertino_icons: ^1.0.5
  collection: ^1.17.1
  webview_flutter: ^4.2.4

dev_dependencies:
  build_runner: ^2.4.4
  dart_code_metrics: ^5.7.4
  drift_dev: ^2.8.2
  flutter_lints: ^2.0.1
  very_good_analysis: ^5.0.0+1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/icons/appstore.png"



flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: fonts/Quicksand-Light.ttf
          weight: 300
        - asset: fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700